config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  get 'sessions/new'

  root 'home#index'
  get '/.well-known/acme-challenge/:id' => 'home#letsencrypt'
  get 'events/my_calendar', to: 'events#my_events'
  get 'email_calendar/:id', to: 'email_calendar#email_to', as: :email_to
  post 'email_calendar', to: 'email_calendar#email_all', as: :email_all
  get 'email_calendar', to: 'email_calendar#index', as: :email_calendar
  get 'terms', to: 'terms#index'
  
  resources :users, only: %i[index update show]
  resources :events
  resources :appointments

  resources :events do
    resources :comments
  end

  match '*path' => redirect('/'), via: [:get]

  # devise_for :users, controllers: {
  #   sessions: 'users/sessions'
  # }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/email_calendar_controller.rb
# frozen_string_literal: true

class EmailCalendarController < ApplicationController
  def email_to
    return unless current_user.admin?

    puts '****emailed'
    @user = User.find(params[:id])
    if @user
      mail = UserMailer.notice_email(@user, 'GeeklyCon Schedule', '', get_users_events(@user), 'ALL')
      mail.deliver_later
    end
    redirect_to :back
  end

  def email_all
    @email_all_params = email_all_params
    return unless @email_all_params[:email_body]
    return unless @email_all_params[:day]
    return unless @email_all_params[:subject]
    return unless current_user.admin?

    users = if @email_all_params[:admin_only] == 'false'
              User.all
            else
              User.where(admin: true)
            end
    users.all.each do |user|
      events = get_users_events(user, @email_all_params[:day])
      mail = UserMailer.notice_email(
        user,
        @email_all_params[:subject],
        @email_all_params[:email_body],
        events,
        @email_all_params[:day]
      )
      mail.deliver_later
    end
    redirect_to :back
  end

  def index; end

  private

  def get_users_events(user, day = 'ALL')
    events = if day == 'ALL'
               user.all_events.where(date: Event.active_event_dates)
             else
               user.all_events.where(date: day)
             end
    format_user_events(events)
  end

  def format_user_events(events)
    render_to_string partial: 'email_calendar/email_events', locals: { events: events }
  end

  def email_all_params
    params.require(:email).permit(:day, :subject, :email_body, :admin_only)
  end
end

app/views/email_calendar/_email_events.html.slim
- events.each do |event|
  h3
    = image_tag("https://www.geeklyinc.com/images/gc18/icon-cal-#{event.category_name.downcase}.png", size: 40, alt: event.category_name)
    = link_to(event.name, event_url(event))
  p
    = "#{event.date}"
    br
    = event.time_period
    br
    = event.location
    = event.description_md.html_safe
  hr

app/views/email_calendar/index.html.slim
.container
  .row
    .col-md-12
      h2 Email Schedule to all users

      div Hi there, please don't mess with this if you don't know what this is. Its a tool to email users schedules. It will email, everyone.
      - event_dates = Event.active_dates_and_text + [['ALL', 'ALL']]
      = simple_form_for(:email, url: email_all_path, method: :post, html: {class: 'usa-form-large'}) do |f|
        = f.input :subject, as: :text,  input_html: {class: 'form-control', required: true}
        = f.input :email_body, as: :text,  input_html: {class: 'form-control', required: true}
        = f.input :day, :collection => event_dates, input_html: {required: true}
        = f.input :admin_only, :collection => [["true", "true"], ["false","false"]]


        = f.button :submit, "Send email to ALL USERS", class: "btn btn-lg btn-primary btn-block", data: { confirm: 'Are you sure you want to email all users!?' }