config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  get 'sessions/new'

  root 'home#index'
  get '/.well-known/acme-challenge/:id' => 'home#letsencrypt'
  get 'events/my_calendar', to: 'events#my_events'
  get 'email_calendar/:id', to: 'email_calendar#email_to', as: :email_to
  post 'email_calendar', to: 'email_calendar#email_all', as: :email_all
  get 'email_calendar', to: 'email_calendar#index', as: :email_calendar
  get 'terms', to: 'terms#index'
  
  resources :users, only: %i[index update show]
  resources :events
  resources :appointments

  resources :events do
    resources :comments
  end

  match '*path' => redirect('/'), via: [:get]

  # devise_for :users, controllers: {
  #   sessions: 'users/sessions'
  # }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_add_to_calendar.html.slim
= link_to 'Export to google calendar', "https://calendar.google.com/calendar/render?#{event.event_cal_params}", target: '_blank'

app/views/shared/_footer.html.slim
.footer
  .row.justify-content-center
    = link_to "Privacy policy", "https://geeklyinc.com/privacy-policy/"
    | &nbsp|&nbsp
    = link_to "Terms of use", "/terms"

app/views/shared/_header.html.slim
- if user_signed_in?
  nav.navbar.navbar-expand-md.navbar-dark.fixed-top
    = link_to "GeeklyCon Calendar", root_path, class: "navbar-brand"
    button[class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="true" aria-label="Toggle navigation"]
      span.navbar-toggler-icon
    .collapse.navbar-collapse id="navbarsExampleDefault"
      ul.navbar-nav.mr-auto
        li[class="nav-item #{active_page_class(events_path(hide_full_games: 1))}"]
          = link_to "Schedule", events_path(hide_full_games: 1), class: 'nav-link'
        li[class="nav-item #{active_page_class(events_my_calendar_path)}"]
          = link_to "My schedule", events_my_calendar_path, class: 'nav-link'
        li[class="nav-item #{active_page_class(events_path(hide_full_games: 1, official_event: 1))}"]
          = link_to "Official Events", events_path(hide_full_games: 1, official_event: 1), class: 'nav-link'
        li[class="nav-item #{active_page_class(events_path(hide_full_games: 1, panel: 1))}"]
          = link_to "Panels", events_path(hide_full_games: 1, panel: 1), class: 'nav-link'
        li[class="nav-item #{active_page_class(events_path(hide_full_games: 1, game: 1))}"]
          = link_to "Games", events_path(hide_full_games: 1, game: 1), class: 'nav-link'
        li[class="nav-item #{active_page_class(events_path(hide_full_games: 1, outing: 1))}"]
          = link_to "Outings", events_path(hide_full_games: 1, outing: 1), class: 'nav-link'
        - if current_user.admin?
          li[class="nav-item #{active_page_class(users_path)}"]
            = link_to "View users (admin only)", users_path, class: 'nav-link'
        li[class="nav-item #{active_page_class(edit_user_registration_path)}"]
          = link_to "Edit profile", edit_user_registration_path, class: 'nav-link'
        - if current_user.admin?
          li[class="nav-item #{active_page_class(email_calendar_path)}"]
            = link_to "Email Schedule (admin only)", email_calendar_path, class: 'nav-link'
      .form-inline.my-2.my-lg-0
        - if !user_signed_in?
          = link_to "Sign Up", new_user_registration_path, class: 'btn btn-outline-light my-2 my-sm-0 mx-1'
          = link_to "Sign In", new_user_session_path, class: 'btn btn-outline-success my-2 my-sm-0 mx-1'
        - else
          = button_to "Sign out", destroy_user_session_path , :method => :delete, class: 'btn btn-outline-warning my-2 my-sm-0'

app/views/shared/_modify_attendee.html.slim
- if event.owner_id == current_user.id
  = button_tag "My event", class: "disabled btn btn-sm btn-light btn-block", disabled: true
- elsif @my_event
  - appointment = @user_appointments.find {|a| a.event_id == event.id}
  = simple_form_for appointment, url: appointment_path(appointment), method: :delete do |f|
    = f.hidden_field :path, value: "#{request.fullpath}#event-id-#{event.id}"
    = f.button :submit, "Remove me", class: "btn btn-sm btn-danger btn-block"
- elsif event.attendee_count >= event.max_attendee_count
  - if event.category != 'game'
    = content_tag :div, "Event full", class: "disabled btn btn-sm btn-light btn-block", "data-toggle"=>"tooltip", "data-placement"=>"top", title: "This event is full, but all offical events and panels are first come first serve."
  - else
    = content_tag :div, "Event full", class: "disabled btn btn-sm btn-light btn-block"
- else
  = simple_form_for Appointment.new do |f|
    = f.hidden_field :event_id, value: event.id
    = f.hidden_field :path, value: "#{request.fullpath}#event-id-#{event.id}"
    = f.button :submit, "Add to my calendar", class: "btn btn-sm btn-primary btn-block"

app/views/shared/_nav.html.slim
/ ul.list-reset
/   - if user_signed_in?
/     li.inline-block.mr1 = link_to "View events", events_path
/     li.inline-block.mr1 = link_to "View users", users_path
/     li.inline-block.mr1 = link_to "Edit profile", edit_user_registration_path
/     li.inline-block.mr1 = button_to "Sign out", destroy_user_session_path , :method => :delete
/   - else
/     li.inline-block.mr1 = link_to "Sign Up", new_user_registration_path
/     li.inline-block.mr1 = link_to "Sign In", new_user_session_path