config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  get 'sessions/new'

  root 'home#index'
  get '/.well-known/acme-challenge/:id' => 'home#letsencrypt'
  get 'events/my_calendar', to: 'events#my_events'
  get 'email_calendar/:id', to: 'email_calendar#email_to', as: :email_to
  post 'email_calendar', to: 'email_calendar#email_all', as: :email_all
  get 'email_calendar', to: 'email_calendar#index', as: :email_calendar
  get 'terms', to: 'terms#index'
  
  resources :users, only: %i[index update show]
  resources :events
  resources :appointments

  resources :events do
    resources :comments
  end

  match '*path' => redirect('/'), via: [:get]

  # devise_for :users, controllers: {
  #   sessions: 'users/sessions'
  # }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: events
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  date        :date
#  category    :string
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null

require 'redcarpet'
require 'redcarpet/render_strip'
require 'uri'

class Event < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  validates :date, presence: true
  validates :category, presence: true
  validates :location, presence: true
  validates :max_attendees, numericality: { only_integer: true, greater_than: 1, less_than_or_equal_to: 500 }, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true

  has_many :appointments, dependent: :destroy
  has_many :users, through: :appointments
  has_many :comments, dependent: :destroy
  attr_accessor :start_time_hour, :end_time_hour, :start_time_minute, :end_time_minute, :end_time_hour, :end_time_am_pm, :start_time_am_pm

  # scope :hide_full_games -> {(where('max_attendees<current_attendees'))}
  scope :official_event, -> { where(category: 'official_event') }
  scope :panel, -> { where(category: 'panel') }
  scope :game, -> { where(category: 'game') }
  scope :outing, -> { where(category: 'outing') }
  # scope :hide_past_events, -> {(where('date !~* ?', '18'))}
  # https://www.sitepoint.com/dynamically-chain-scopes-to-clean-up-large-sql-queries/

  def self.category_order
    cat_order = sanitize_sql_array(
      [
        'case when category = ? then 1 when category = ? then 2 when category = ? then 3 when category = ? then 4 end',
        'official_event',
        'panel',
        'outing',
        'game'
      ]
    )
    order(Arel.sql(cat_order))
  end

  def self.active_event_dates
    active_dates_and_text.map do |d|
      d[1]
    end
  end

  def self.active_dates_and_text
    [
      ['June 22, 2023', '06/22/23'],
      ['June 23, 2023', '06/23/23'],
      ['June 24, 2023', '06/24/23'],
      ['June 25, 2023', '06/25/23'],
    ]
  end

  def attendee_count
    return current_attendees unless current_attendees.nil?

    update(current_attendees: users.count)
    users.count
  end

  def update_attendee_count
    update(current_attendees: users.count)
  end

  def max_attendee_count
    max_attendees || 500
  end

  def time_period
    if start_time && end_time
      "#{day_of_week} <strong class='even-space'>#{start_time.strftime('%I:%M%p')}-#{end_time.strftime('%I:%M%p')}</strong>".html_safe
    else
      ''
    end
  end

  def hours
    if start_time && end_time
      "<strong class='even-space'>#{start_time.strftime('%I:%M%p')}-#{end_time.strftime('%I:%M%p')}</strong>".html_safe
    else
      ''
    end
  end

  def self.event_categories(user)
    if user.admin
      %w[official_event panel game outing]
    else
      %w[game outing]
    end
  end

  def description_md
    Event.markdown.render(description)
  end

  def self.markdown
    @renderer ||= Redcarpet::Render::HTML.new(no_links: true, hard_wrap: true, no_images: true, filter_html: true)
    @markdown ||= Redcarpet::Markdown.new(@renderer)
  end

  def self.internal_markdown
    @renderer ||= Redcarpet::Render::HTML.new(no_links: false, hard_wrap: true, no_images: true, filter_html: false)
    @markdown ||= Redcarpet::Markdown.new(@renderer)
  end

  def category_name
    return 'Game' if category.blank?

    cat_names = { game: 'Game', official_event: 'Geekly', outing: 'Outing', panel: 'Panel' }
    cat_names[category.to_sym]
  end

  def owner_name
    @owner ||= User.where(id: owner_id)
    if !@owner.blank?
      @owner.first.name
    else
      ''
    end
  end

  def owner_email
    @owner ||= User.where(id: owner_id)
    if !@owner.blank?
      @owner.first.email
    else
      ''
    end
  end

  def day_of_week
    days = %w[Sunday Monday Tuesday Wednesday Thursday Friday Saturday]
    days[Date.strptime(date, '%m/%d/%y').wday]
  end

  def self.send_chain(methods)
    methods.inject(self, :send)
  end

  def event_cal_params
    day = Date.strptime(date, '%m/%d/%y')
    fdate = day.strftime('%Y%m%d')
    'action=TEMPLATE' \
      "&dates=#{fdate}T#{start_time.strftime('%H%M')}00/" \
      "#{fdate}T#{end_time.strftime('%H%M')}00" \
      '&ctz=America/New_York' \
      "&text=#{uri_ampcode(name)}" \
      "&details=#{uri_ampcode(description)}" \
      "&location=#{uri_ampcode(location)}"
  end

  def uri_ampcode(str)
    CGI.escape(str).gsub('&', '%26')
  end

  def conflicting_events
    @conflicting_events ||= Event.where(
      "(start_time > :start AND start_time < :end) OR
       (end_time > :start AND end_time < :end) OR
       (start_time < :start AND end_time > :end) OR
       (start_time = :start AND end_time > :end) OR
       (start_time < :start and end_time = :end)
      ", start: start_time, end: end_time
    )
                                 .where.not(id: id)
                                 .where(date: date)
                                 .order(:start_time).category_order.order(:id)
  end

  def prior_events
    @prior_events ||= Event.where(end_time: start_time)
                           .where.not(id: id)
                           .where(date: date)
                           .order(:start_time).category_order.order(:id)
  end

  def upcoming_events
    @upcoming_events ||= Event.where(start_time: end_time)
                              .where.not(id: id)
                              .where(date: date)
                              .order(:start_time).category_order.order(:id)
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_filter_params, only: %i[index my_events]
  load_and_authorize_resource

  def index
    @current_path = events_path
    @events = filter_events
    @users_events = current_user.events
    @user_appointments = current_user.appointments
  end

  def my_events
    @current_path = events_my_calendar_path
    # owned_events = Event.where(owner_id: current_user.id, category: event_filter_categories).order(:start_time)
    # @users_events = (
    #   current_user.events.where(category: event_filter_categories).order(:start_time) +
    #   owned_events
    # ).uniq
    @user_appointments = current_user.appointments
    # @events = @users_events
    @events = current_user.all_events
    @users_events = @events
    render 'my_calendar'
  end

  def show
    @event = Event.includes(:users, :comments).find(params[:id])
    @event.update(current_attendees: @event.users.count)
    @users_events = current_user.events
    @user_appointments = current_user.appointments
    @my_event = @users_events.find { |e| e.id == @event.id } || @event.owner_id == current_user.id
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      flash[:success] = 'saved'
      redirect_to @event
    else
      flash[:error] = 'an error occurred'
      render 'new'
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to @event
    else
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])

    @event.destroy
    redirect_to events_path
  end

  private

  def load_filter_params
    @hide_full_games = filter_params[:hide_full_games].present?
  end

  def filter_params
    params.permit(:official_event, :panel, :game, :outing, :hide_full_games, :show_past_events)
  end

  def filter_events
    Event.where(category: event_filter_categories).order(:start_time).category_order.order(:id)
    # if !category_params.empty?
    #   Event.send_chain(category_params).order(:start_time).order(:id)
    # else
    #   Event.all.order(:start_time).order(:id)
    # end
  end

  def category_params
    # if params[:show_past_events]
    params.permit(:official_event, :panel, :game, :outing).to_h.keys
    # else
    #   keys = params.permit(:official_event, :panel, :game, :outing).to_h.keys
    #   keys.push(:hide_past_events)
    # end
  end

  def event_filter_categories
    cat = []
    cat.push('official_event') if filter_params[:official_event]
    cat.push('panel') if filter_params[:panel]
    cat.push('game') if filter_params[:game]
    cat.push('outing') if filter_params[:outing]
    if cat.empty?
      %w[official_event panel game outing]
    else
      cat
    end
  end

  def event_params
    if params[:event][:owner_id].blank? || !current_user.admin?
      params[:event][:owner_id] = current_user.id
    end

    if current_user.admin?
      params.require(:event).permit(:name, :description, :date, :start_time, :end_time, :category, :max_attendees, :owner_id, :location, :image)
    else
      params.require(:event).permit(:name, :description, :date, :start_time, :end_time, :category, :max_attendees, :owner_id, :location)
    end
  end
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
end

app/views/events/_calendar.html.slim
.row.my2
  .col-md-4
  .col-md-4
    .row
      .col-md-12
        h2.text-center Create a game!
        p Want to play a game, but need players? Create your own event and people can sign up to join!
    .row
      .col-md-12
        = link_to 'Create event', new_event_path, class: "btn btn-sm btn-primary btn-block font-white-important"
  .col-md-4
hr
= form_tag(@current_path, method: :get) do |f|
  .row.my1
    .col-md-1
    .col-md-8
      .form-check.form-check-inline
        = check_box_tag 'official_event', '1', params[:official_event] == "1", class: 'form-check-input'
        = label_tag 'official_event', 'Official Event', class: 'form-check-label' do
          = image_tag("https://www.geeklyinc.com/images/gc18/icon-cal-geekly.png", size: 20, alt: "")
          = " Official Event"
      .form-check.form-check-inline
        = check_box_tag 'panel', '1', params[:panel] == "1", class: 'form-check-input'
        = label_tag 'panel', 'Panel', class: 'form-check-label' do
          = image_tag("https://www.geeklyinc.com/images/gc18/icon-cal-panel.png", size: 20, alt: "")
          = " Panel"
      .form-check.form-check-inline
        = check_box_tag 'outing', '1', params[:outing] == "1", class: 'form-check-input'
        = label_tag 'outing', 'Outing', class: 'form-check-label' do
          = image_tag("https://www.geeklyinc.com/images/gc18/icon-cal-outing.png", size: 20, alt: "")
          = " Outing"
      .form-check.form-check-inline
        = check_box_tag 'game', '1', params[:game] == "1", class: 'form-check-input'
        = label_tag 'game', 'Game', class: 'form-check-label' do
          = image_tag("https://www.geeklyinc.com/images/gc18/icon-cal-game.png", size: 20, alt: "")
          = " Game"
      .form-check.form-check-inline
        = check_box_tag 'hide_full_games', '1', params[:hide_full_games] == "1", class: 'form-check-input'
        = label_tag 'hide_full_games', 'Hide full games', class: 'form-check-label' do
          = "Hide full games"
      / .form-check.form-check-inline
      /   = check_box_tag 'show_past_events', '1', params[:show_past_events] == "1", class: 'form-check-input'
      /   = label_tag 'show_past_events', 'Show past events', class: 'form-check-label' do
      /     = "Show past events"
    .col-md-2
      = button_tag "Filter", class: "btn btn-sm btn-info btn-block"
    .col-md-1

hr
.row.my1
  .col-md-1
  .col-md-10
    i All official events and panels are free and open to the public. Individual games have limited capacity. All times are Eastern Daylight Time (EDT).
  .col-md-1
- Event.active_dates_and_text.each do |e_date|
  .row.my2.px2
    .col-md-6
      - day_name = DateTime.strptime(e_date[1], '%m/%d/%y').strftime("%A")
      h2.h2.mb-3.font-weight-normal = "#{day_name}, #{e_date[0]}"
  = render partial: 'event_preview', :locals => {events: @events, event_date: e_date[1]}

app/views/events/_comments.html.slim
.row.mt2
  .col-md-1
  .col-md-11
    h2 Comments
.row
  .col-md-12
    hr
- if @event.comments.count == 0
  .row
    .col-md-1
    .col-md-11
      p No Comments. Somebody say something!
- @event.comments.each do |comment|
  - next if comment.user_id.nil?
  .row
    .col-md-1
    .col-md-11
      .row
        .col-md-3
          .row
            .col-md-12
              strong = comment.user.name
          .row
            .col-md-12
              = comment.created_at
        .col-md-8
          p = comment.text_md.html_safe
        .col-md-1
          - if current_user.id == @event.owner_id || current_user.admin || current_user.id == comment.user_id
            = link_to 'Delete', event_comment_path(event_id: @event.id, id: comment.id),
                class: 'btn btn-sm btn-danger btn-block',
                method: :delete,
                data: { confirm: 'Are you sure you want to delete? This cannot be undone' }
      .row
        .col-md-12
          hr

app/views/events/_conflicting_events.html.slim
- conflicting_events = @event.conflicting_events
- prior_events = @event.prior_events
- upcoming_events = @event.upcoming_events
- if (conflicting_events.count +  prior_events.count + upcoming_events.count) > 0
  .row
    .col-md-12
      hr
  .row
    .col-md-1
    .col-md-11
      h2 Other events
  = render partial: 'conflicting_events_section', locals: {events: prior_events, event_heading: 'Prior events'}
  = render partial: 'conflicting_events_section', locals: {events: conflicting_events, event_heading: 'Conflicting events'}
  = render partial: 'conflicting_events_section', locals: {events: upcoming_events, event_heading: 'Upcoming events'}

app/views/events/_conflicting_events_section.html.slim
- if events.count > 0
    .row
      .col-md-1
      .col-md-11
        .h3 = event_heading
    - events.each do |event|
      .row
        .col-md-1
        .col-md-2 = event.hours
        .col-md-9
          strong
            span.px1
              - image_type = event.category == 'official_event' ? 'geekly' : event.category
              = image_tag("https://www.geeklyinc.com/images/gc18/icon-cal-#{image_type}.png", size: 20, alt: "")
            = link_to event.name, event_path(event)
    hr

app/views/events/_event_preview.html.slim
- events.each do |event|
  - next unless event.date == event_date
  - @my_event = @users_events.find { |e| e.id == event.id } || event.owner_id == current_user.id
  - next if !@my_event && @hide_full_games && event.category == 'game' && event.attendee_count >= event.max_attendee_count
  .row[class="table-row-#{event.category} table-row-#{event.category}-hover px1 py1 my1 event-border rounded calendar-preview-row mouse-hover" id="" onclick="window.location.href='#{event_path(event)}'"]
    a[id="event-id-#{event.id}" class="anchor"]
    .col-md-1 
      = image_tag("https://www.geeklyinc.com/images/gc18/icon-cal-#{event.category_name.downcase}.png", size: 40, alt: event.category_name)
    .col-md-2
      strong = link_to event.name, event_path(event)
    .col-md-1 = event.time_period
    - if event.location.length > 24
      .col-md-1 = "#{event.location[0..24]}..."
    - if event.location.length <= 24
      .col-md-1 = event.location
    .col-md-1 
      span[title='number attending the panel']
        = "#{event.attendee_count || 0}/#{event.max_attendee_count || 1}"
    .col-md-4
      - append_text = '...' + content_tag(:strong, link_to('read more', event_path(event)))
      = partial_html(event.description_md, 151, append_text).html_safe
    .col-md-2 
      .row
        .col-md-12
          = render partial: 'shared/modify_attendee', locals: {event: event }
      .row.mt2
        .col-md-12
          = render partial: 'shared/add_to_calendar', locals: {event: event}

app/views/events/_form.html.slim
.row
  .col-md-2
  .col-md-8
    = simple_form_for @event, html: {class: "usa-form-large"} do |f|
      .row.my-2
        .col-md-5
          = f.input :name, input_html: {class: 'form-control'}
      .row.my-2
        .col-md-3
          = f.input :max_attendees, input_html: {class: 'form-control'}
      .row.my-2
        .col-md-8
          = f.input :description, as: :text,  input_html: {class: 'form-control'}
      .row.my-2
        .col-md-5
          = f.input :category, :collection => Event.event_categories(current_user), input_html:{ class: 'form-control'}
      .row.my-2
        .col-md-5
          = f.input :location, input_html: { value: f.object.location || 'Gameroom', class: 'form-control' }
      .row.my-2
        .col-md-5
          = f.input :date, :collection => Event.active_dates_and_text
      .row.my-2
        .col-md-5
          = f.input :start_time, as: :time, html5: true, input_html:{ class: 'form-control'}
        .col-md-5
          = f.input :end_time, as: :time, html5: true, input_html:{ class: 'form-control'}
      - if current_user.admin?
        .row
          .col-md-12
            h3 Admin only options
        .row.my-2
          .col-md-5
            = f.input :owner_id, :collection => User.all.order(:last_name), input_html: { class: 'form-control' }
        .row.my-2
          .col-md-5
            = f.input :image, input_html: {class: 'form-control'}
      .row.my-2
        .col-md-3
          = f.button :submit, submit_text, class: "btn btn-lg btn-primary btn-block"
  .col-md-2

app/views/events/edit.html.slim
.container
  .row
    .col-md-12
      h1.h1.mb-3.font-weight-normal.remove-margin
          = image_tag('header.jpg', class: 'img-fluid', alt: 'Calendar')
  .row
    .col-md-2
    .col-md-8
      h2.h1.mb-3.font-weight-normal Edit Event
    .col-md-2
  .row
    .col-md-2
    .col-md-2
      = link_to 'Cancel Edit', event_path(@event), class: 'btn btn-sm btn-primary btn-block'
    .col-md-8
  = render partial: 'form', locals: {submit_text: 'Update'}
  = render 'shared/footer'

app/views/events/index.html.slim
.container
  .row.pb1
    .col-md-12
      h1.h1.mb-3.font-weight-normal.remove-margin
        = image_tag('header.jpg', class: 'img-fluid', alt: 'Calendar')
      = render partial: 'calendar'
  = render 'shared/footer'

app/views/events/my_calendar.html.slim
.container
  .row.pb1
    .col-md-12
      h1.h1.mb-3.font-weight-normal.remove-margin
          = image_tag('header.jpg', class: 'img-fluid', alt: 'Calendar')
  .row
    .col-md-12
      h2.h1.mb-3.font-weight-normal.text-center My calendar
  .row
    .col-md-4
    .col-md-4
      p This is your calendar. It shows the events you've added to your schedule.
    .col-md-4
  .row
    .col-md-12
      = render partial: 'calendar'
  = render 'shared/footer'

app/views/events/new.html.slim
.container
  .row
    .col-md-12
      h1.h1.mb-3.font-weight-normal.remove-margin
          = image_tag('header.jpg', class: 'img-fluid', alt: 'Calendar')
  .row
    .col-md-2
    .col-md-8
      h2.h1.mb-3.font-weight-normal New Event
    .col-md-2
  = render partial: 'form', locals: {submit_text: 'Create event'}
  = render 'shared/footer'

app/views/events/show.html.slim
.container
  .row
    .col-md-12
      h1.h1.mb-3.font-weight-normal.remove-margin
        = image_tag("https://www.geeklyinc.com/images/gc18/cal-banner-#{@event.category}.jpg", class: 'img-fluid', alt: @event.category)
  - if current_user.id == @event.owner_id || current_user.admin
    .row.pb2
      .col-md-2
      .col-md-8
        .row
          .col-md-3
          .col-md-5
           strong Event owner options:
          .col-md-2
            = link_to "Edit", edit_event_path(@event), class: 'btn btn-sm btn-info btn-block'
          .col-md-2
            = link_to 'Delete', event_path(@event),
              class: 'btn btn-sm btn-danger btn-block',
              method: :delete,
              data: { confirm: 'Are you sure you want to delete? This cannot be undone' }
      .col-md-2
  .row.pb2
    .col-md-1
    .col-md-10
      .card
        .card-header[class="table-row-#{@event.category} event-border"]
          .row
            .col-md-1 
              = image_tag("https://www.geeklyinc.com/images/gc18/icon-cal-#{@event.category_name.downcase}.png", size: 40, alt: @event.category_name)
            .col-md-8.my-auto
              h4 = "#{@event.name}"
            .col-md-3
              .row
                .col-md-12
                  = render partial: 'shared/modify_attendee', locals: {event: @event }
              .row.mt1
                .col-md-12
                  = render partial: 'shared/add_to_calendar', locals: {event: @event}
        .card-body
          - if !@event.image.nil? && !@event.image.empty?
            .card-text
              .row.mb2
                .col-md-12.text-center
                  = image_tag @event.image, style: "max-width: 100%; max-height: 400px;"
              hr
          .card-text
            .row
              .col-md-2
                strong Name:
              .col-md-10
                = @event.name
          .card-text
            .row
              .col-md-2
                strong Owner:
              .col-md-10
                = @event.owner_name
          - if current_user.admin
            .card-text
              .row
                .col-md-2
                  strong Owner Email (admin only):
                .col-md-10
                  = @event.owner_email
          .card-text
            .row
              .col-md-2
                strong Location:
              .col-md-10
                = @event.location
          .card-text
            .row
              .col-md-2
                strong Date:
              .col-md-10
                = @event.date
          .card-text
            .row
              .col-md-2
              .col-md-10
                strong
                  = @event.time_period
          .card-text
            .row
              .col-md-2
                strong Description:
              .col-md-10
                = @event.description_md.html_safe
          .card-text
            - if current_user.id == @event.owner_id
              p 
                | You own this event, so you can see full names of attendees to help organize the event
            - if current_user.admin
              p
                | You are an admin, so you can see full names of attendees.
          .card-text
            .row
              .col-md-2
                - showAttendees = (current_user.id == @event.owner_id || current_user.admin) || (@event.category == 'game' || @event.category == 'outing')
                strong Attendees:
              .col-md-2
                = "#{@event.attendee_count}/#{@event.max_attendees}"
                - if showAttendees
                  a data-toggle='collapse' href='#user-list' role='button' aria-expanded='false' aria-controls='user-list' = " show"
          .collapse.card-text.collapse.multi-collapse id="user-list"
            - if showAttendees
              ul
                - @event.users.each do |user|
                  - if user.first_name && user.last_name
                    li
                      - if current_user.id == @event.owner_id || current_user.admin
                        = user.name
                      - else
                        = "#{user.first_name} #{user.last_name[0..0] if user.last_name}"
                      - unless user.twitter.blank? || user.twitter.include?('@gmail.com') || user.twitter =~ /.+\@/
                        = " - "
                        = link_to "#{"@" unless user.twitter.include?("@")}#{user.twitter}", "http://www.twitter.com/#{user.twitter}", target: "_blank", rel: "alternate"
          - if current_user.admin
            .card-text
              .row
                .col-md-2
                  strong Emails (admin only feature):
                .col-md-2
                  a data-toggle='collapse' href='#user-emails' role='button' aria-expanded='false' aria-controls='user-emails' = " show emails"
            .collapse.card-text.collapse.multi-collapse id="user-emails"
              ul
                - @event.users.each do |user|
                  li
                    = user.email
    .col-md-1
  = render partial: 'conflicting_events'
  = render 'shared/footer'